version: "3.8"

services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        depends_on:
            - db

    db:
        image: mariadb:11.4.2
        ports:
            - "3307:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=rootpassword
            - MYSQL_DATABASE=myapp
            - MYSQL_USER=myuser
            - MYSQL_PASSWORD=mypassword

volumes:
    mariadb_data:
