services:
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        networks:
            - mynetwork
        depends_on:
            - db

    backend:
        build: ./backend
        ports:
            - "8000:8000"
        volumes:
            - ./backend/app:/app
        depends_on:
            db:
                condition: service_healthy
        networks:
            - mynetwork

    db:
        build: ./database
        image: mariadb:11.4.2
        ports:
            - "3306:3306"
        volumes:
            - mariadb_data:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        networks:
            - mynetwork
        healthcheck:
            test: ["CMD", "mariadb", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    mariadb_data:

networks:
    mynetwork:
        driver: bridge
